#!/bin/bash -ex

if [ $# -lt 5 ]; then
  echo "Usage: $0 <API> <Cloud Run service name> <api_config.yaml> <project_name> <region_name>"
  exit 1
fi

api=$1
service=$2
api_config=$3
project_name=$4
region_name=${4:-europe-west1}
this_dir=$(dirname "$(readlink -f "$0")")

gcloud endpoints services deploy api_descriptor.pb $3 --project=$project_name
config_id=$(curl -H "Authorization: Bearer $(gcloud auth print-access-token)" \
            https://servicemanagement.googleapis.com/v1/services/$api/configs | \
            jq -r '.serviceConfigs[0].id')
echo Deploying for $config_id

image_tag=$($this_dir/build_esp_image -s $api -p $project_name -c $config_id | grep "IMAGE:" | cut -f2 -d' ')
gcloud run deploy $service \
  --allow-unauthenticated \
  --set-env-vars=ESPv2_ARGS=^++^--transcoding_preserve_proto_field_names++--envoy_connection_buffer_limit_bytes=10485760 \
  --platform managed \
  --project=$project_name \
  --region=$region_name \
  --image="$image_tag"
